from src.fmmlx_mlm_structure.model_element import ModelElement


class ChangeSuggestion:
    """Change suggestions generated by model-deepening analysis processes. Each change suggestion refers to an
    original model element and its changed variant. Note that model elements may be composite
    (a class may have instances), leading to side effects."""
    def __init__(self, old_element, new_element):
        self.og_model_element: ModelElement = old_element
        self.changed_model_element: ModelElement = new_element

    def get_og_model_element(self) -> ModelElement:
        return self.og_model_element

    def get_changed_model_element(self) -> ModelElement:
        return self.changed_model_element
